spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: https://auth-service-v1-zu2s.onrender.com
          predicates:
            - Path=/auth/**
        - id: broker-integration-service
          uri: https://broker-integration-service-v1.onrender.com
          predicates:
            - Path=/broker-integration/**
        - id: portfolio-service
          uri: https://portfolio-service-v1.onrender.com
          predicates:
            - Path=/portfolio/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "https://vertiq-prod.vercel.app"
              - "https://vertiq-dev.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
server:
  port: 8080

jwt:
  secret: "vertiqSuperSecretKey2025!@#Random1234567890"
